---
- name: Listen for events on a webhook
  hosts: all

  ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  ## Define the conditions we are looking for

  rules:
    - name: Simon Says
      condition: event.payload.message is match("simon says*")
      action:
        run_job_template:
          name: Clone Repo
          extra_vars:
            git_dest: event.payload.git_dest
