---
- name: Listen for events on a webhook
  hosts: all

  ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  ## Define the conditions we are looking for

  rules:
    - name: Simon Says
      condition: event.payload.message is match("simon says*")
      actions:
        - debug:
            msg: "Starting clone to {{ event.payload.git_dest }} "
        - run_job_template:
            name: Clone Repo
            organization: Default
            job_args:
              extra_vars:
                git_dest: "{{ event.payload.git_dest }}"
        - debug:
            msg: "Executed  clone to {{ event.payload.git_dest }}"
