---
- name: Webhook Example
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Say Hello when webhook triggered
      condition: event.payload.message is defined
      action:
        run_playbook:
          name: hello.yml
